name: sanhak
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  speech_to_text: ^7.0.0
  noise_meter: ^5.0.2
  permission_handler: ^11.0.0
  get: ^4.6.6

dependency_overrides:
  audio_streamer: 4.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: SolmoeFont
      fonts:
        - asset: assets/fonts/솔뫼 김대건OTF Medium.otf

  uses-material-design: true

  assets:
    - assets/images/배경화면.png
    - assets/images/카카오로그인버튼.png
    - assets/images/게임방법.png
    - assets/images/지난기록.png
    - assets/images/연주하기.png
