name: sanhak
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  speech_to_text: ^7.0.0
  noise_meter: ^5.0.2
  permission_handler: ^11.0.0
  get: ^4.6.6
  percent_indicator: ^4.2.2
  simple_animations: ^5.2.0
  just_audio: ^0.9.36
  dio: ^5.9.0
  flutter_secure_storage: ^9.2.4
  kakao_flutter_sdk_user: ^1.9.7+3
  flutter_dotenv: ^6.0.0
  intl: ^0.19.0

dependency_overrides:
  audio_streamer: 4.2.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  fonts:
    - family: SolmoeFont
      fonts:
        - asset: assets/fonts/솔뫼 김대건OTF Medium.otf

  uses-material-design: true

  assets:
    - .env
    - assets/images/background/배경화면1.png
    - assets/images/background/배경화면2.png
    - assets/images/background/곡아이콘.png

    - assets/images/buttons/카카오로그인버튼.png
    - assets/images/buttons/게임방법.png
    - assets/images/buttons/지난기록.png
    - assets/images/buttons/연주하기.png

    - assets/images/buttons/나가기.png
    - assets/images/buttons/모범연주듣기.png
    - assets/images/buttons/내연주듣기.png

    - assets/images/icons/북.png
    - assets/images/icons/징.png
    - assets/images/icons/장구.png
    - assets/images/icons/꽹과리.png
    - assets/images/icons/스피커.png

    - assets/images/icons/wrong_북.png
    - assets/images/icons/wrong_징.png
    - assets/images/icons/wrong_장구.png
    - assets/images/icons/wrong_꽹과리.png


    - assets/images/texts/GREAT!.png

    - assets/music/easy.mp3
    - assets/music/mid.mp3
    - assets/music/hard.mp3

    - assets/dummy/easy_janggu.json
    - assets/dummy/easy_drum.json
    - assets/dummy/easy_ggueng.json
    - assets/dummy/easy_jing.json

    - assets/dummy/hard_janggu.json
    - assets/dummy/hard_drum.json
    - assets/dummy/hard_ggueng.json
    - assets/dummy/hard_jing.json

    - assets/dummy/mid_drum.json
    - assets/dummy/mid_ggueng.json
    - assets/dummy/mid_jing.json
    - assets/dummy/mid_janggu.json